// Google Fonts（OFL ライセンス）の DotGothic16 / Press Start 2P を自前ホスト用にダウンロードする
// usage: node scripts/fetch-fonts.mjs
// → public/fonts/fonts.css と public/fonts/*.woff2 を生成
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'public', 'fonts');
const CSS_URL = 'https://fonts.googleapis.com/css2?family=DotGothic16&family=Press+Start+2P&display=swap';
// woff2 を返してもらうためのモダンブラウザ UA
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

mkdirSync(OUT, { recursive: true });

const cssRes = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
if (!cssRes.ok) throw new Error(`css fetch failed: ${cssRes.status}`);
let css = await cssRes.text();

const urls = [...new Set([...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]))];
console.log(`fonts: ${urls.length} files`);

let i = 0;
for (const url of urls) {
  const family = /\/s\/([a-z0-9]+)\//i.exec(url)?.[1] ?? 'font';
  // URL 末尾（ハッシュ付きファイル名）をそのまま使い、衝突しないようにする
  const base = url.split('/').pop() ?? `${i}.woff2`;
  const file = `${family}-${base}`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`font fetch failed: ${url} ${res.status}`);
  writeFileSync(join(OUT, file), Buffer.from(await res.arrayBuffer()));
  css = css.replaceAll(url, `./${file}`);
  i += 1;
  if (i % 20 === 0) console.log(`  ${i}/${urls.length}`);
}

const header = [
  '/* DotGothic16 (c) Fontworks Inc. / Press Start 2P (c) CodeMan38',
  '   Both licensed under the SIL Open Font License 1.1 — https://scripts.sil.org/OFL',
  '   Generated by scripts/fetch-fonts.mjs */',
  '',
].join('\n');
writeFileSync(join(OUT, 'fonts.css'), header + css);
console.log('wrote fonts.css');
